### ISSUE TITLE
users model

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/account_tracker#2]
Construct a Users, "full name - `full_name`," from their first, middle, last & suffix.

Doing so helps simplify things on the frontend.

This should be included in the User results at `/request/`

Current:
```
first_name: Adam
middle_name: G
last_name: Butcher
suffix: Jr.
```

Goal:
```
first_name: Adam
middle_name: G
last_name: Butcher
suffix: Jr.
full_name: Adam G Butcher Jr.
```

**Comment by adabutch** [comment]
We also need a date stamp to indicate when the request for the User came through.

For example, if I created a new User today - the stamp would read (generically) `02/12/2019`.

I'm open to whatever name fits, maybe - `requested_date` or `initiation_date` ... however, I think we should reserve `created_on` for when the User was actually approved in the interface by an Admin?

Total open to whatever works here, happy to discuss/think about workflow actions.

**Comment by sethCOB** [comment]
Depending on how closely we want to follow Active Directory's schema, the attribute `created` is set the moment the object is placed into the directory. So I think reserving `created_on` (or `created`) in this application would be useful for consistency purposes.

`requested_date` sounds fine to me to track the actual submission process.

**Comment by charlesbrandt** [comment]
This should be available now on the account_request api.
