### ISSUE TITLE
service profile (id + name)

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/account_tracker#5]
When querying a service profile (`/api/profile/`), it would be helpful to tack on the name of the service.

**_For example (current):_**
`"services": [2,...]`

**_Want:_**
`"services": [{"id": 2, "name": "3D Home Architect 5.0 Deluxe"},...]`

**Comment by charlesbrandt** [comment]
Setting the field with a many=True allows DRF to return all service details (677c065abad991d7e4f95d73291fbea8d48d7d9b)
